title: Love Your Database
description: > # this means to ignore newlines until "baseurl:"
  The Relational Model is poorly understood and worse applied. 
  
  This blog is dedicated to the proposition that the Relational Model is the best way to manage data yet devised. 
  It is not the only way, but it is the best way. And although SQL is an abomination, it is what we have to work with.
  
  This blog discusses how to get the most out of your database. Things you might not know your database can do,
  and how to implement ore of your application in the database.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lydb.xyz" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Guyren Howe # add your name
author-img: guyren.jpg # add your photo
about-author: Full-stack developer, teacher and database expert.
social-twitter: unclouded # add your Twitter handle
social-github: gisborne # add your Github handle
social-linkedin: guyren # add your Linkedin handle
social-email: guyren@relevantlogic.com # add your Email address

# Disqus
discus-identifier: gisborne # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
